/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_auth_5f1_2e6_2eproto__INCLUDED
#define PROTOBUF_C_auth_5f1_2e6_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _In__Gov__Uidai__Authserver__Protobuf__Pid In__Gov__Uidai__Authserver__Protobuf__Pid;
typedef struct _In__Gov__Uidai__Authserver__Protobuf__Demo In__Gov__Uidai__Authserver__Protobuf__Demo;
typedef struct _In__Gov__Uidai__Authserver__Protobuf__Pi In__Gov__Uidai__Authserver__Protobuf__Pi;
typedef struct _In__Gov__Uidai__Authserver__Protobuf__Pa In__Gov__Uidai__Authserver__Protobuf__Pa;
typedef struct _In__Gov__Uidai__Authserver__Protobuf__Pfa In__Gov__Uidai__Authserver__Protobuf__Pfa;
typedef struct _In__Gov__Uidai__Authserver__Protobuf__Dob In__Gov__Uidai__Authserver__Protobuf__Dob;
typedef struct _In__Gov__Uidai__Authserver__Protobuf__Bios In__Gov__Uidai__Authserver__Protobuf__Bios;
typedef struct _In__Gov__Uidai__Authserver__Protobuf__Bio In__Gov__Uidai__Authserver__Protobuf__Bio;
typedef struct _In__Gov__Uidai__Authserver__Protobuf__Pv In__Gov__Uidai__Authserver__Protobuf__Pv;


/* --- enums --- */

typedef enum _In__Gov__Uidai__Authserver__Protobuf__Pi__Gender {
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__GENDER__F = 1,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__GENDER__M = 2,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__GENDER__T = 3
} In__Gov__Uidai__Authserver__Protobuf__Pi__Gender;
typedef enum _In__Gov__Uidai__Authserver__Protobuf__Pi__Dobt {
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__DOBT__V = 1,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__DOBT__D = 2,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__DOBT__A = 3
} In__Gov__Uidai__Authserver__Protobuf__Pi__Dobt;
typedef enum _In__Gov__Uidai__Authserver__Protobuf__LangCode {
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Assamese = 1,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Bengali = 2,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Gujarati = 5,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Hindi = 6,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Kannada = 7,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Malayalam = 11,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Manipuri = 12,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Marathi = 13,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Oriya = 15,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Punjabi = 16,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Tamil = 20,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Telugu = 21,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__Urdu = 22
} In__Gov__Uidai__Authserver__Protobuf__LangCode;
typedef enum _In__Gov__Uidai__Authserver__Protobuf__Ms {
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__MS__E = 1,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__MS__P = 2,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__MS__F = 3
} In__Gov__Uidai__Authserver__Protobuf__Ms;
typedef enum _In__Gov__Uidai__Authserver__Protobuf__BioType {
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIO_TYPE__FMR = 0,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIO_TYPE__FIR = 1,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIO_TYPE__IIR = 2
} In__Gov__Uidai__Authserver__Protobuf__BioType;
typedef enum _In__Gov__Uidai__Authserver__Protobuf__Position {
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_IRIS = 1,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_IRIS = 2,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_INDEX = 3,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_LITTLE = 4,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_MIDDLE = 5,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_RING = 6,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_THUMB = 7,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_INDEX = 8,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_LITTLE = 9,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_MIDDLE = 10,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_RING = 11,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_THUMB = 12,
  IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__UNKNOWN = 13
} In__Gov__Uidai__Authserver__Protobuf__Position;

/* --- messages --- */

struct  _In__Gov__Uidai__Authserver__Protobuf__Pid
{
  ProtobufCMessage base;
  char *ver;
  char *ts;
  In__Gov__Uidai__Authserver__Protobuf__Demo *demo;
  In__Gov__Uidai__Authserver__Protobuf__Bios *bios;
  In__Gov__Uidai__Authserver__Protobuf__Pv *pv;
};
#define IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PID__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&in__gov__uidai__authserver__protobuf__pid__descriptor) \
    , NULL, NULL, NULL, NULL, NULL }


struct  _In__Gov__Uidai__Authserver__Protobuf__Demo
{
  ProtobufCMessage base;
  protobuf_c_boolean has_lang;
  In__Gov__Uidai__Authserver__Protobuf__LangCode lang;
  In__Gov__Uidai__Authserver__Protobuf__Pi *pi;
  In__Gov__Uidai__Authserver__Protobuf__Pa *pa;
  In__Gov__Uidai__Authserver__Protobuf__Pfa *pfa;
};
#define IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__DEMO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&in__gov__uidai__authserver__protobuf__demo__descriptor) \
    , 0,0, NULL, NULL, NULL }


struct  _In__Gov__Uidai__Authserver__Protobuf__Pi
{
  ProtobufCMessage base;
  protobuf_c_boolean has_ms;
  In__Gov__Uidai__Authserver__Protobuf__Ms ms;
  char *name;
  protobuf_c_boolean has_mv;
  int32_t mv;
  char *lname;
  protobuf_c_boolean has_lmv;
  int32_t lmv;
  protobuf_c_boolean has_gender;
  In__Gov__Uidai__Authserver__Protobuf__Pi__Gender gender;
  In__Gov__Uidai__Authserver__Protobuf__Dob *dob;
  protobuf_c_boolean has_dobt;
  In__Gov__Uidai__Authserver__Protobuf__Pi__Dobt dobt;
  protobuf_c_boolean has_age;
  int32_t age;
  char *email;
  char *phone;
};
#define IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&in__gov__uidai__authserver__protobuf__pi__descriptor) \
    , 0,0, NULL, 0,0, NULL, 0,0, 0,0, NULL, 0,0, 0,0, NULL, NULL }


struct  _In__Gov__Uidai__Authserver__Protobuf__Pa
{
  ProtobufCMessage base;
  protobuf_c_boolean has_ms;
  In__Gov__Uidai__Authserver__Protobuf__Ms ms;
  char *co;
  char *house;
  char *street;
  char *lm;
  char *loc;
  char *vtc;
  char *subdist;
  char *dist;
  char *state;
  char *pc;
  char *po;
};
#define IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&in__gov__uidai__authserver__protobuf__pa__descriptor) \
    , 0,0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _In__Gov__Uidai__Authserver__Protobuf__Pfa
{
  ProtobufCMessage base;
  protobuf_c_boolean has_ms;
  In__Gov__Uidai__Authserver__Protobuf__Ms ms;
  char *av;
  protobuf_c_boolean has_mv;
  int32_t mv;
  char *lav;
  protobuf_c_boolean has_lmv;
  int32_t lmv;
};
#define IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PFA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&in__gov__uidai__authserver__protobuf__pfa__descriptor) \
    , 0,0, NULL, 0,0, NULL, 0,0 }


struct  _In__Gov__Uidai__Authserver__Protobuf__Dob
{
  ProtobufCMessage base;
  int32_t year;
  protobuf_c_boolean has_month;
  int32_t month;
  protobuf_c_boolean has_day;
  int32_t day;
};
#define IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__DOB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&in__gov__uidai__authserver__protobuf__dob__descriptor) \
    , 0, 0,0, 0,0 }


struct  _In__Gov__Uidai__Authserver__Protobuf__Bios
{
  ProtobufCMessage base;
  size_t n_bio;
  In__Gov__Uidai__Authserver__Protobuf__Bio **bio;
};
#define IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIOS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&in__gov__uidai__authserver__protobuf__bios__descriptor) \
    , 0,NULL }


struct  _In__Gov__Uidai__Authserver__Protobuf__Bio
{
  ProtobufCMessage base;
  In__Gov__Uidai__Authserver__Protobuf__BioType type;
  In__Gov__Uidai__Authserver__Protobuf__Position posh;
  ProtobufCBinaryData content;
};
#define IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&in__gov__uidai__authserver__protobuf__bio__descriptor) \
    , 0, 0, {0,NULL} }


struct  _In__Gov__Uidai__Authserver__Protobuf__Pv
{
  ProtobufCMessage base;
  char *otp;
  char *pin;
};
#define IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PV__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&in__gov__uidai__authserver__protobuf__pv__descriptor) \
    , NULL, NULL }


/* In__Gov__Uidai__Authserver__Protobuf__Pid methods */
void   in__gov__uidai__authserver__protobuf__pid__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pid         *message);
size_t in__gov__uidai__authserver__protobuf__pid__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pid   *message);
size_t in__gov__uidai__authserver__protobuf__pid__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pid   *message,
                      uint8_t             *out);
size_t in__gov__uidai__authserver__protobuf__pid__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pid   *message,
                      ProtobufCBuffer     *buffer);
In__Gov__Uidai__Authserver__Protobuf__Pid *
       in__gov__uidai__authserver__protobuf__pid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   in__gov__uidai__authserver__protobuf__pid__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pid *message,
                      ProtobufCAllocator *allocator);
/* In__Gov__Uidai__Authserver__Protobuf__Demo methods */
void   in__gov__uidai__authserver__protobuf__demo__init
                     (In__Gov__Uidai__Authserver__Protobuf__Demo         *message);
size_t in__gov__uidai__authserver__protobuf__demo__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Demo   *message);
size_t in__gov__uidai__authserver__protobuf__demo__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Demo   *message,
                      uint8_t             *out);
size_t in__gov__uidai__authserver__protobuf__demo__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Demo   *message,
                      ProtobufCBuffer     *buffer);
In__Gov__Uidai__Authserver__Protobuf__Demo *
       in__gov__uidai__authserver__protobuf__demo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   in__gov__uidai__authserver__protobuf__demo__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Demo *message,
                      ProtobufCAllocator *allocator);
/* In__Gov__Uidai__Authserver__Protobuf__Pi methods */
void   in__gov__uidai__authserver__protobuf__pi__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pi         *message);
size_t in__gov__uidai__authserver__protobuf__pi__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pi   *message);
size_t in__gov__uidai__authserver__protobuf__pi__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pi   *message,
                      uint8_t             *out);
size_t in__gov__uidai__authserver__protobuf__pi__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pi   *message,
                      ProtobufCBuffer     *buffer);
In__Gov__Uidai__Authserver__Protobuf__Pi *
       in__gov__uidai__authserver__protobuf__pi__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   in__gov__uidai__authserver__protobuf__pi__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pi *message,
                      ProtobufCAllocator *allocator);
/* In__Gov__Uidai__Authserver__Protobuf__Pa methods */
void   in__gov__uidai__authserver__protobuf__pa__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pa         *message);
size_t in__gov__uidai__authserver__protobuf__pa__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pa   *message);
size_t in__gov__uidai__authserver__protobuf__pa__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pa   *message,
                      uint8_t             *out);
size_t in__gov__uidai__authserver__protobuf__pa__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pa   *message,
                      ProtobufCBuffer     *buffer);
In__Gov__Uidai__Authserver__Protobuf__Pa *
       in__gov__uidai__authserver__protobuf__pa__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   in__gov__uidai__authserver__protobuf__pa__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pa *message,
                      ProtobufCAllocator *allocator);
/* In__Gov__Uidai__Authserver__Protobuf__Pfa methods */
void   in__gov__uidai__authserver__protobuf__pfa__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pfa         *message);
size_t in__gov__uidai__authserver__protobuf__pfa__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pfa   *message);
size_t in__gov__uidai__authserver__protobuf__pfa__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pfa   *message,
                      uint8_t             *out);
size_t in__gov__uidai__authserver__protobuf__pfa__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pfa   *message,
                      ProtobufCBuffer     *buffer);
In__Gov__Uidai__Authserver__Protobuf__Pfa *
       in__gov__uidai__authserver__protobuf__pfa__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   in__gov__uidai__authserver__protobuf__pfa__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pfa *message,
                      ProtobufCAllocator *allocator);
/* In__Gov__Uidai__Authserver__Protobuf__Dob methods */
void   in__gov__uidai__authserver__protobuf__dob__init
                     (In__Gov__Uidai__Authserver__Protobuf__Dob         *message);
size_t in__gov__uidai__authserver__protobuf__dob__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Dob   *message);
size_t in__gov__uidai__authserver__protobuf__dob__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Dob   *message,
                      uint8_t             *out);
size_t in__gov__uidai__authserver__protobuf__dob__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Dob   *message,
                      ProtobufCBuffer     *buffer);
In__Gov__Uidai__Authserver__Protobuf__Dob *
       in__gov__uidai__authserver__protobuf__dob__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   in__gov__uidai__authserver__protobuf__dob__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Dob *message,
                      ProtobufCAllocator *allocator);
/* In__Gov__Uidai__Authserver__Protobuf__Bios methods */
void   in__gov__uidai__authserver__protobuf__bios__init
                     (In__Gov__Uidai__Authserver__Protobuf__Bios         *message);
size_t in__gov__uidai__authserver__protobuf__bios__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Bios   *message);
size_t in__gov__uidai__authserver__protobuf__bios__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Bios   *message,
                      uint8_t             *out);
size_t in__gov__uidai__authserver__protobuf__bios__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Bios   *message,
                      ProtobufCBuffer     *buffer);
In__Gov__Uidai__Authserver__Protobuf__Bios *
       in__gov__uidai__authserver__protobuf__bios__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   in__gov__uidai__authserver__protobuf__bios__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Bios *message,
                      ProtobufCAllocator *allocator);
/* In__Gov__Uidai__Authserver__Protobuf__Bio methods */
void   in__gov__uidai__authserver__protobuf__bio__init
                     (In__Gov__Uidai__Authserver__Protobuf__Bio         *message);
size_t in__gov__uidai__authserver__protobuf__bio__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Bio   *message);
size_t in__gov__uidai__authserver__protobuf__bio__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Bio   *message,
                      uint8_t             *out);
size_t in__gov__uidai__authserver__protobuf__bio__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Bio   *message,
                      ProtobufCBuffer     *buffer);
In__Gov__Uidai__Authserver__Protobuf__Bio *
       in__gov__uidai__authserver__protobuf__bio__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   in__gov__uidai__authserver__protobuf__bio__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Bio *message,
                      ProtobufCAllocator *allocator);
/* In__Gov__Uidai__Authserver__Protobuf__Pv methods */
void   in__gov__uidai__authserver__protobuf__pv__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pv         *message);
size_t in__gov__uidai__authserver__protobuf__pv__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pv   *message);
size_t in__gov__uidai__authserver__protobuf__pv__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pv   *message,
                      uint8_t             *out);
size_t in__gov__uidai__authserver__protobuf__pv__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pv   *message,
                      ProtobufCBuffer     *buffer);
In__Gov__Uidai__Authserver__Protobuf__Pv *
       in__gov__uidai__authserver__protobuf__pv__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   in__gov__uidai__authserver__protobuf__pv__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pv *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*In__Gov__Uidai__Authserver__Protobuf__Pid_Closure)
                 (const In__Gov__Uidai__Authserver__Protobuf__Pid *message,
                  void *closure_data);
typedef void (*In__Gov__Uidai__Authserver__Protobuf__Demo_Closure)
                 (const In__Gov__Uidai__Authserver__Protobuf__Demo *message,
                  void *closure_data);
typedef void (*In__Gov__Uidai__Authserver__Protobuf__Pi_Closure)
                 (const In__Gov__Uidai__Authserver__Protobuf__Pi *message,
                  void *closure_data);
typedef void (*In__Gov__Uidai__Authserver__Protobuf__Pa_Closure)
                 (const In__Gov__Uidai__Authserver__Protobuf__Pa *message,
                  void *closure_data);
typedef void (*In__Gov__Uidai__Authserver__Protobuf__Pfa_Closure)
                 (const In__Gov__Uidai__Authserver__Protobuf__Pfa *message,
                  void *closure_data);
typedef void (*In__Gov__Uidai__Authserver__Protobuf__Dob_Closure)
                 (const In__Gov__Uidai__Authserver__Protobuf__Dob *message,
                  void *closure_data);
typedef void (*In__Gov__Uidai__Authserver__Protobuf__Bios_Closure)
                 (const In__Gov__Uidai__Authserver__Protobuf__Bios *message,
                  void *closure_data);
typedef void (*In__Gov__Uidai__Authserver__Protobuf__Bio_Closure)
                 (const In__Gov__Uidai__Authserver__Protobuf__Bio *message,
                  void *closure_data);
typedef void (*In__Gov__Uidai__Authserver__Protobuf__Pv_Closure)
                 (const In__Gov__Uidai__Authserver__Protobuf__Pv *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    in__gov__uidai__authserver__protobuf__lang_code__descriptor;
extern const ProtobufCEnumDescriptor    in__gov__uidai__authserver__protobuf__ms__descriptor;
extern const ProtobufCEnumDescriptor    in__gov__uidai__authserver__protobuf__bio_type__descriptor;
extern const ProtobufCEnumDescriptor    in__gov__uidai__authserver__protobuf__position__descriptor;
extern const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pid__descriptor;
extern const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__demo__descriptor;
extern const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pi__descriptor;
extern const ProtobufCEnumDescriptor    in__gov__uidai__authserver__protobuf__pi__gender__descriptor;
extern const ProtobufCEnumDescriptor    in__gov__uidai__authserver__protobuf__pi__dobt__descriptor;
extern const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pa__descriptor;
extern const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pfa__descriptor;
extern const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__dob__descriptor;
extern const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__bios__descriptor;
extern const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__bio__descriptor;
extern const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pv__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_auth_5f1_2e6_2eproto__INCLUDED */
