/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "auth_1.6.pb-c.h"
void   in__gov__uidai__authserver__protobuf__pid__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pid         *message)
{
  static In__Gov__Uidai__Authserver__Protobuf__Pid init_value = IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PID__INIT;
  *message = init_value;
}
size_t in__gov__uidai__authserver__protobuf__pid__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pid *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t in__gov__uidai__authserver__protobuf__pid__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pid *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t in__gov__uidai__authserver__protobuf__pid__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pid *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
In__Gov__Uidai__Authserver__Protobuf__Pid *
       in__gov__uidai__authserver__protobuf__pid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (In__Gov__Uidai__Authserver__Protobuf__Pid *)
     protobuf_c_message_unpack (&in__gov__uidai__authserver__protobuf__pid__descriptor,
                                allocator, len, data);
}
void   in__gov__uidai__authserver__protobuf__pid__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pid *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   in__gov__uidai__authserver__protobuf__demo__init
                     (In__Gov__Uidai__Authserver__Protobuf__Demo         *message)
{
  static In__Gov__Uidai__Authserver__Protobuf__Demo init_value = IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__DEMO__INIT;
  *message = init_value;
}
size_t in__gov__uidai__authserver__protobuf__demo__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Demo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__demo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t in__gov__uidai__authserver__protobuf__demo__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Demo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__demo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t in__gov__uidai__authserver__protobuf__demo__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Demo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__demo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
In__Gov__Uidai__Authserver__Protobuf__Demo *
       in__gov__uidai__authserver__protobuf__demo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (In__Gov__Uidai__Authserver__Protobuf__Demo *)
     protobuf_c_message_unpack (&in__gov__uidai__authserver__protobuf__demo__descriptor,
                                allocator, len, data);
}
void   in__gov__uidai__authserver__protobuf__demo__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Demo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__demo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   in__gov__uidai__authserver__protobuf__pi__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pi         *message)
{
  static In__Gov__Uidai__Authserver__Protobuf__Pi init_value = IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__INIT;
  *message = init_value;
}
size_t in__gov__uidai__authserver__protobuf__pi__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pi *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pi__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t in__gov__uidai__authserver__protobuf__pi__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pi *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pi__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t in__gov__uidai__authserver__protobuf__pi__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pi *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pi__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
In__Gov__Uidai__Authserver__Protobuf__Pi *
       in__gov__uidai__authserver__protobuf__pi__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (In__Gov__Uidai__Authserver__Protobuf__Pi *)
     protobuf_c_message_unpack (&in__gov__uidai__authserver__protobuf__pi__descriptor,
                                allocator, len, data);
}
void   in__gov__uidai__authserver__protobuf__pi__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pi *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pi__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   in__gov__uidai__authserver__protobuf__pa__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pa         *message)
{
  static In__Gov__Uidai__Authserver__Protobuf__Pa init_value = IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PA__INIT;
  *message = init_value;
}
size_t in__gov__uidai__authserver__protobuf__pa__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pa *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pa__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t in__gov__uidai__authserver__protobuf__pa__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pa *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pa__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t in__gov__uidai__authserver__protobuf__pa__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pa *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pa__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
In__Gov__Uidai__Authserver__Protobuf__Pa *
       in__gov__uidai__authserver__protobuf__pa__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (In__Gov__Uidai__Authserver__Protobuf__Pa *)
     protobuf_c_message_unpack (&in__gov__uidai__authserver__protobuf__pa__descriptor,
                                allocator, len, data);
}
void   in__gov__uidai__authserver__protobuf__pa__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pa *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pa__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   in__gov__uidai__authserver__protobuf__pfa__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pfa         *message)
{
  static In__Gov__Uidai__Authserver__Protobuf__Pfa init_value = IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PFA__INIT;
  *message = init_value;
}
size_t in__gov__uidai__authserver__protobuf__pfa__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pfa *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pfa__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t in__gov__uidai__authserver__protobuf__pfa__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pfa *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pfa__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t in__gov__uidai__authserver__protobuf__pfa__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pfa *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pfa__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
In__Gov__Uidai__Authserver__Protobuf__Pfa *
       in__gov__uidai__authserver__protobuf__pfa__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (In__Gov__Uidai__Authserver__Protobuf__Pfa *)
     protobuf_c_message_unpack (&in__gov__uidai__authserver__protobuf__pfa__descriptor,
                                allocator, len, data);
}
void   in__gov__uidai__authserver__protobuf__pfa__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pfa *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pfa__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   in__gov__uidai__authserver__protobuf__dob__init
                     (In__Gov__Uidai__Authserver__Protobuf__Dob         *message)
{
  static In__Gov__Uidai__Authserver__Protobuf__Dob init_value = IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__DOB__INIT;
  *message = init_value;
}
size_t in__gov__uidai__authserver__protobuf__dob__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Dob *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__dob__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t in__gov__uidai__authserver__protobuf__dob__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Dob *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__dob__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t in__gov__uidai__authserver__protobuf__dob__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Dob *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__dob__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
In__Gov__Uidai__Authserver__Protobuf__Dob *
       in__gov__uidai__authserver__protobuf__dob__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (In__Gov__Uidai__Authserver__Protobuf__Dob *)
     protobuf_c_message_unpack (&in__gov__uidai__authserver__protobuf__dob__descriptor,
                                allocator, len, data);
}
void   in__gov__uidai__authserver__protobuf__dob__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Dob *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__dob__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   in__gov__uidai__authserver__protobuf__bios__init
                     (In__Gov__Uidai__Authserver__Protobuf__Bios         *message)
{
  static In__Gov__Uidai__Authserver__Protobuf__Bios init_value = IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIOS__INIT;
  *message = init_value;
}
size_t in__gov__uidai__authserver__protobuf__bios__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Bios *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__bios__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t in__gov__uidai__authserver__protobuf__bios__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Bios *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__bios__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t in__gov__uidai__authserver__protobuf__bios__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Bios *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__bios__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
In__Gov__Uidai__Authserver__Protobuf__Bios *
       in__gov__uidai__authserver__protobuf__bios__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (In__Gov__Uidai__Authserver__Protobuf__Bios *)
     protobuf_c_message_unpack (&in__gov__uidai__authserver__protobuf__bios__descriptor,
                                allocator, len, data);
}
void   in__gov__uidai__authserver__protobuf__bios__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Bios *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__bios__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   in__gov__uidai__authserver__protobuf__bio__init
                     (In__Gov__Uidai__Authserver__Protobuf__Bio         *message)
{
  static In__Gov__Uidai__Authserver__Protobuf__Bio init_value = IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIO__INIT;
  *message = init_value;
}
size_t in__gov__uidai__authserver__protobuf__bio__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Bio *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__bio__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t in__gov__uidai__authserver__protobuf__bio__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Bio *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__bio__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t in__gov__uidai__authserver__protobuf__bio__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Bio *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__bio__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
In__Gov__Uidai__Authserver__Protobuf__Bio *
       in__gov__uidai__authserver__protobuf__bio__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (In__Gov__Uidai__Authserver__Protobuf__Bio *)
     protobuf_c_message_unpack (&in__gov__uidai__authserver__protobuf__bio__descriptor,
                                allocator, len, data);
}
void   in__gov__uidai__authserver__protobuf__bio__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Bio *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__bio__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   in__gov__uidai__authserver__protobuf__pv__init
                     (In__Gov__Uidai__Authserver__Protobuf__Pv         *message)
{
  static In__Gov__Uidai__Authserver__Protobuf__Pv init_value = IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PV__INIT;
  *message = init_value;
}
size_t in__gov__uidai__authserver__protobuf__pv__get_packed_size
                     (const In__Gov__Uidai__Authserver__Protobuf__Pv *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pv__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t in__gov__uidai__authserver__protobuf__pv__pack
                     (const In__Gov__Uidai__Authserver__Protobuf__Pv *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pv__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t in__gov__uidai__authserver__protobuf__pv__pack_to_buffer
                     (const In__Gov__Uidai__Authserver__Protobuf__Pv *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pv__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
In__Gov__Uidai__Authserver__Protobuf__Pv *
       in__gov__uidai__authserver__protobuf__pv__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (In__Gov__Uidai__Authserver__Protobuf__Pv *)
     protobuf_c_message_unpack (&in__gov__uidai__authserver__protobuf__pv__descriptor,
                                allocator, len, data);
}
void   in__gov__uidai__authserver__protobuf__pv__free_unpacked
                     (In__Gov__Uidai__Authserver__Protobuf__Pv *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &in__gov__uidai__authserver__protobuf__pv__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor in__gov__uidai__authserver__protobuf__pid__field_descriptors[5] =
{
  {
    "ver",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pid, ver),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pid, ts),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "demo",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pid, demo),
    &in__gov__uidai__authserver__protobuf__demo__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bios",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pid, bios),
    &in__gov__uidai__authserver__protobuf__bios__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pv",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pid, pv),
    &in__gov__uidai__authserver__protobuf__pv__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned in__gov__uidai__authserver__protobuf__pid__field_indices_by_name[] = {
  3,   /* field[3] = bios */
  2,   /* field[2] = demo */
  4,   /* field[4] = pv */
  1,   /* field[1] = ts */
  0,   /* field[0] = ver */
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__pid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pid__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Pid",
  "Pid",
  "In__Gov__Uidai__Authserver__Protobuf__Pid",
  "in.gov.uidai.authserver.protobuf",
  sizeof(In__Gov__Uidai__Authserver__Protobuf__Pid),
  5,
  in__gov__uidai__authserver__protobuf__pid__field_descriptors,
  in__gov__uidai__authserver__protobuf__pid__field_indices_by_name,
  1,  in__gov__uidai__authserver__protobuf__pid__number_ranges,
  (ProtobufCMessageInit) in__gov__uidai__authserver__protobuf__pid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor in__gov__uidai__authserver__protobuf__demo__field_descriptors[4] =
{
  {
    "lang",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Demo, has_lang),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Demo, lang),
    &in__gov__uidai__authserver__protobuf__lang_code__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pi",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Demo, pi),
    &in__gov__uidai__authserver__protobuf__pi__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pa",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Demo, pa),
    &in__gov__uidai__authserver__protobuf__pa__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pfa",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Demo, pfa),
    &in__gov__uidai__authserver__protobuf__pfa__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned in__gov__uidai__authserver__protobuf__demo__field_indices_by_name[] = {
  0,   /* field[0] = lang */
  2,   /* field[2] = pa */
  3,   /* field[3] = pfa */
  1,   /* field[1] = pi */
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__demo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__demo__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Demo",
  "Demo",
  "In__Gov__Uidai__Authserver__Protobuf__Demo",
  "in.gov.uidai.authserver.protobuf",
  sizeof(In__Gov__Uidai__Authserver__Protobuf__Demo),
  4,
  in__gov__uidai__authserver__protobuf__demo__field_descriptors,
  in__gov__uidai__authserver__protobuf__demo__field_indices_by_name,
  1,  in__gov__uidai__authserver__protobuf__demo__number_ranges,
  (ProtobufCMessageInit) in__gov__uidai__authserver__protobuf__demo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue in__gov__uidai__authserver__protobuf__pi__gender__enum_values_by_number[3] =
{
  { "F", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__GENDER__F", 1 },
  { "M", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__GENDER__M", 2 },
  { "T", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__GENDER__T", 3 },
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__pi__gender__value_ranges[] = {
{1, 0},{0, 3}
};
const ProtobufCEnumValueIndex in__gov__uidai__authserver__protobuf__pi__gender__enum_values_by_name[3] =
{
  { "F", 0 },
  { "M", 1 },
  { "T", 2 },
};
const ProtobufCEnumDescriptor in__gov__uidai__authserver__protobuf__pi__gender__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Pi.Gender",
  "Gender",
  "In__Gov__Uidai__Authserver__Protobuf__Pi__Gender",
  "in.gov.uidai.authserver.protobuf",
  3,
  in__gov__uidai__authserver__protobuf__pi__gender__enum_values_by_number,
  3,
  in__gov__uidai__authserver__protobuf__pi__gender__enum_values_by_name,
  1,
  in__gov__uidai__authserver__protobuf__pi__gender__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue in__gov__uidai__authserver__protobuf__pi__dobt__enum_values_by_number[3] =
{
  { "V", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__DOBT__V", 1 },
  { "D", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__DOBT__D", 2 },
  { "A", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__PI__DOBT__A", 3 },
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__pi__dobt__value_ranges[] = {
{1, 0},{0, 3}
};
const ProtobufCEnumValueIndex in__gov__uidai__authserver__protobuf__pi__dobt__enum_values_by_name[3] =
{
  { "A", 2 },
  { "D", 1 },
  { "V", 0 },
};
const ProtobufCEnumDescriptor in__gov__uidai__authserver__protobuf__pi__dobt__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Pi.Dobt",
  "Dobt",
  "In__Gov__Uidai__Authserver__Protobuf__Pi__Dobt",
  "in.gov.uidai.authserver.protobuf",
  3,
  in__gov__uidai__authserver__protobuf__pi__dobt__enum_values_by_number,
  3,
  in__gov__uidai__authserver__protobuf__pi__dobt__enum_values_by_name,
  1,
  in__gov__uidai__authserver__protobuf__pi__dobt__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor in__gov__uidai__authserver__protobuf__pi__field_descriptors[11] =
{
  {
    "ms",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, has_ms),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, ms),
    &in__gov__uidai__authserver__protobuf__ms__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mv",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, has_mv),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, mv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lname",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, lname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lmv",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, has_lmv),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, lmv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gender",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, has_gender),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, gender),
    &in__gov__uidai__authserver__protobuf__pi__gender__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dob",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, dob),
    &in__gov__uidai__authserver__protobuf__dob__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dobt",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, has_dobt),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, dobt),
    &in__gov__uidai__authserver__protobuf__pi__dobt__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "age",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, has_age),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, age),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, email),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pi, phone),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned in__gov__uidai__authserver__protobuf__pi__field_indices_by_name[] = {
  8,   /* field[8] = age */
  6,   /* field[6] = dob */
  7,   /* field[7] = dobt */
  9,   /* field[9] = email */
  5,   /* field[5] = gender */
  4,   /* field[4] = lmv */
  3,   /* field[3] = lname */
  0,   /* field[0] = ms */
  2,   /* field[2] = mv */
  1,   /* field[1] = name */
  10,   /* field[10] = phone */
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__pi__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pi__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Pi",
  "Pi",
  "In__Gov__Uidai__Authserver__Protobuf__Pi",
  "in.gov.uidai.authserver.protobuf",
  sizeof(In__Gov__Uidai__Authserver__Protobuf__Pi),
  11,
  in__gov__uidai__authserver__protobuf__pi__field_descriptors,
  in__gov__uidai__authserver__protobuf__pi__field_indices_by_name,
  1,  in__gov__uidai__authserver__protobuf__pi__number_ranges,
  (ProtobufCMessageInit) in__gov__uidai__authserver__protobuf__pi__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor in__gov__uidai__authserver__protobuf__pa__field_descriptors[12] =
{
  {
    "ms",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, has_ms),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, ms),
    &in__gov__uidai__authserver__protobuf__ms__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "co",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, co),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "house",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, house),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "street",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, street),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lm",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, lm),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loc",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, loc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vtc",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, vtc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subdist",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, subdist),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dist",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, dist),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pc",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, pc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "po",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pa, po),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned in__gov__uidai__authserver__protobuf__pa__field_indices_by_name[] = {
  1,   /* field[1] = co */
  8,   /* field[8] = dist */
  2,   /* field[2] = house */
  4,   /* field[4] = lm */
  5,   /* field[5] = loc */
  0,   /* field[0] = ms */
  10,   /* field[10] = pc */
  11,   /* field[11] = po */
  9,   /* field[9] = state */
  3,   /* field[3] = street */
  7,   /* field[7] = subdist */
  6,   /* field[6] = vtc */
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__pa__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pa__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Pa",
  "Pa",
  "In__Gov__Uidai__Authserver__Protobuf__Pa",
  "in.gov.uidai.authserver.protobuf",
  sizeof(In__Gov__Uidai__Authserver__Protobuf__Pa),
  12,
  in__gov__uidai__authserver__protobuf__pa__field_descriptors,
  in__gov__uidai__authserver__protobuf__pa__field_indices_by_name,
  1,  in__gov__uidai__authserver__protobuf__pa__number_ranges,
  (ProtobufCMessageInit) in__gov__uidai__authserver__protobuf__pa__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor in__gov__uidai__authserver__protobuf__pfa__field_descriptors[5] =
{
  {
    "ms",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pfa, has_ms),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pfa, ms),
    &in__gov__uidai__authserver__protobuf__ms__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "av",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pfa, av),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mv",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pfa, has_mv),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pfa, mv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lav",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pfa, lav),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lmv",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pfa, has_lmv),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pfa, lmv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned in__gov__uidai__authserver__protobuf__pfa__field_indices_by_name[] = {
  1,   /* field[1] = av */
  3,   /* field[3] = lav */
  4,   /* field[4] = lmv */
  0,   /* field[0] = ms */
  2,   /* field[2] = mv */
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__pfa__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pfa__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Pfa",
  "Pfa",
  "In__Gov__Uidai__Authserver__Protobuf__Pfa",
  "in.gov.uidai.authserver.protobuf",
  sizeof(In__Gov__Uidai__Authserver__Protobuf__Pfa),
  5,
  in__gov__uidai__authserver__protobuf__pfa__field_descriptors,
  in__gov__uidai__authserver__protobuf__pfa__field_indices_by_name,
  1,  in__gov__uidai__authserver__protobuf__pfa__number_ranges,
  (ProtobufCMessageInit) in__gov__uidai__authserver__protobuf__pfa__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor in__gov__uidai__authserver__protobuf__dob__field_descriptors[3] =
{
  {
    "year",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Dob, year),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "month",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Dob, has_month),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Dob, month),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "day",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Dob, has_day),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Dob, day),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned in__gov__uidai__authserver__protobuf__dob__field_indices_by_name[] = {
  2,   /* field[2] = day */
  1,   /* field[1] = month */
  0,   /* field[0] = year */
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__dob__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__dob__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Dob",
  "Dob",
  "In__Gov__Uidai__Authserver__Protobuf__Dob",
  "in.gov.uidai.authserver.protobuf",
  sizeof(In__Gov__Uidai__Authserver__Protobuf__Dob),
  3,
  in__gov__uidai__authserver__protobuf__dob__field_descriptors,
  in__gov__uidai__authserver__protobuf__dob__field_indices_by_name,
  1,  in__gov__uidai__authserver__protobuf__dob__number_ranges,
  (ProtobufCMessageInit) in__gov__uidai__authserver__protobuf__dob__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor in__gov__uidai__authserver__protobuf__bios__field_descriptors[1] =
{
  {
    "bio",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Bios, n_bio),
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Bios, bio),
    &in__gov__uidai__authserver__protobuf__bio__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned in__gov__uidai__authserver__protobuf__bios__field_indices_by_name[] = {
  0,   /* field[0] = bio */
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__bios__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__bios__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Bios",
  "Bios",
  "In__Gov__Uidai__Authserver__Protobuf__Bios",
  "in.gov.uidai.authserver.protobuf",
  sizeof(In__Gov__Uidai__Authserver__Protobuf__Bios),
  1,
  in__gov__uidai__authserver__protobuf__bios__field_descriptors,
  in__gov__uidai__authserver__protobuf__bios__field_indices_by_name,
  1,  in__gov__uidai__authserver__protobuf__bios__number_ranges,
  (ProtobufCMessageInit) in__gov__uidai__authserver__protobuf__bios__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor in__gov__uidai__authserver__protobuf__bio__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Bio, type),
    &in__gov__uidai__authserver__protobuf__bio_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "posh",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Bio, posh),
    &in__gov__uidai__authserver__protobuf__position__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Bio, content),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned in__gov__uidai__authserver__protobuf__bio__field_indices_by_name[] = {
  2,   /* field[2] = content */
  1,   /* field[1] = posh */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__bio__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__bio__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Bio",
  "Bio",
  "In__Gov__Uidai__Authserver__Protobuf__Bio",
  "in.gov.uidai.authserver.protobuf",
  sizeof(In__Gov__Uidai__Authserver__Protobuf__Bio),
  3,
  in__gov__uidai__authserver__protobuf__bio__field_descriptors,
  in__gov__uidai__authserver__protobuf__bio__field_indices_by_name,
  1,  in__gov__uidai__authserver__protobuf__bio__number_ranges,
  (ProtobufCMessageInit) in__gov__uidai__authserver__protobuf__bio__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor in__gov__uidai__authserver__protobuf__pv__field_descriptors[2] =
{
  {
    "otp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pv, otp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pin",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(In__Gov__Uidai__Authserver__Protobuf__Pv, pin),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned in__gov__uidai__authserver__protobuf__pv__field_indices_by_name[] = {
  0,   /* field[0] = otp */
  1,   /* field[1] = pin */
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__pv__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor in__gov__uidai__authserver__protobuf__pv__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Pv",
  "Pv",
  "In__Gov__Uidai__Authserver__Protobuf__Pv",
  "in.gov.uidai.authserver.protobuf",
  sizeof(In__Gov__Uidai__Authserver__Protobuf__Pv),
  2,
  in__gov__uidai__authserver__protobuf__pv__field_descriptors,
  in__gov__uidai__authserver__protobuf__pv__field_indices_by_name,
  1,  in__gov__uidai__authserver__protobuf__pv__number_ranges,
  (ProtobufCMessageInit) in__gov__uidai__authserver__protobuf__pv__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue in__gov__uidai__authserver__protobuf__lang_code__enum_values_by_number[13] =
{
  { "Assamese", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__ASSAMESE", 1 },
  { "Bengali", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__BENGALI", 2 },
  { "Gujarati", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__GUJARATI", 5 },
  { "Hindi", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__HINDI", 6 },
  { "Kannada", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__KANNADA", 7 },
  { "Malayalam", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__MALAYALAM", 11 },
  { "Manipuri", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__MANIPURI", 12 },
  { "Marathi", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__MARATHI", 13 },
  { "Oriya", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__ORIYA", 15 },
  { "Punjabi", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__PUNJABI", 16 },
  { "Tamil", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__TAMIL", 20 },
  { "Telugu", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__TELUGU", 21 },
  { "Urdu", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__LANG_CODE__URDU", 22 },
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__lang_code__value_ranges[] = {
{1, 0},{5, 2},{11, 5},{15, 8},{20, 10},{0, 13}
};
const ProtobufCEnumValueIndex in__gov__uidai__authserver__protobuf__lang_code__enum_values_by_name[13] =
{
  { "Assamese", 0 },
  { "Bengali", 1 },
  { "Gujarati", 2 },
  { "Hindi", 3 },
  { "Kannada", 4 },
  { "Malayalam", 5 },
  { "Manipuri", 6 },
  { "Marathi", 7 },
  { "Oriya", 8 },
  { "Punjabi", 9 },
  { "Tamil", 10 },
  { "Telugu", 11 },
  { "Urdu", 12 },
};
const ProtobufCEnumDescriptor in__gov__uidai__authserver__protobuf__lang_code__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.LangCode",
  "LangCode",
  "In__Gov__Uidai__Authserver__Protobuf__LangCode",
  "in.gov.uidai.authserver.protobuf",
  13,
  in__gov__uidai__authserver__protobuf__lang_code__enum_values_by_number,
  13,
  in__gov__uidai__authserver__protobuf__lang_code__enum_values_by_name,
  5,
  in__gov__uidai__authserver__protobuf__lang_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue in__gov__uidai__authserver__protobuf__ms__enum_values_by_number[3] =
{
  { "E", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__MS__E", 1 },
  { "P", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__MS__P", 2 },
  { "F", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__MS__F", 3 },
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__ms__value_ranges[] = {
{1, 0},{0, 3}
};
const ProtobufCEnumValueIndex in__gov__uidai__authserver__protobuf__ms__enum_values_by_name[3] =
{
  { "E", 0 },
  { "F", 2 },
  { "P", 1 },
};
const ProtobufCEnumDescriptor in__gov__uidai__authserver__protobuf__ms__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Ms",
  "Ms",
  "In__Gov__Uidai__Authserver__Protobuf__Ms",
  "in.gov.uidai.authserver.protobuf",
  3,
  in__gov__uidai__authserver__protobuf__ms__enum_values_by_number,
  3,
  in__gov__uidai__authserver__protobuf__ms__enum_values_by_name,
  1,
  in__gov__uidai__authserver__protobuf__ms__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue in__gov__uidai__authserver__protobuf__bio_type__enum_values_by_number[3] =
{
  { "FMR", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIO_TYPE__FMR", 0 },
  { "FIR", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIO_TYPE__FIR", 1 },
  { "IIR", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__BIO_TYPE__IIR", 2 },
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__bio_type__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex in__gov__uidai__authserver__protobuf__bio_type__enum_values_by_name[3] =
{
  { "FIR", 1 },
  { "FMR", 0 },
  { "IIR", 2 },
};
const ProtobufCEnumDescriptor in__gov__uidai__authserver__protobuf__bio_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.BioType",
  "BioType",
  "In__Gov__Uidai__Authserver__Protobuf__BioType",
  "in.gov.uidai.authserver.protobuf",
  3,
  in__gov__uidai__authserver__protobuf__bio_type__enum_values_by_number,
  3,
  in__gov__uidai__authserver__protobuf__bio_type__enum_values_by_name,
  1,
  in__gov__uidai__authserver__protobuf__bio_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue in__gov__uidai__authserver__protobuf__position__enum_values_by_number[13] =
{
  { "LEFT_IRIS", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_IRIS", 1 },
  { "RIGHT_IRIS", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_IRIS", 2 },
  { "LEFT_INDEX", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_INDEX", 3 },
  { "LEFT_LITTLE", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_LITTLE", 4 },
  { "LEFT_MIDDLE", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_MIDDLE", 5 },
  { "LEFT_RING", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_RING", 6 },
  { "LEFT_THUMB", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__LEFT_THUMB", 7 },
  { "RIGHT_INDEX", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_INDEX", 8 },
  { "RIGHT_LITTLE", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_LITTLE", 9 },
  { "RIGHT_MIDDLE", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_MIDDLE", 10 },
  { "RIGHT_RING", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_RING", 11 },
  { "RIGHT_THUMB", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__RIGHT_THUMB", 12 },
  { "UNKNOWN", "IN__GOV__UIDAI__AUTHSERVER__PROTOBUF__POSITION__UNKNOWN", 13 },
};
static const ProtobufCIntRange in__gov__uidai__authserver__protobuf__position__value_ranges[] = {
{1, 0},{0, 13}
};
const ProtobufCEnumValueIndex in__gov__uidai__authserver__protobuf__position__enum_values_by_name[13] =
{
  { "LEFT_INDEX", 2 },
  { "LEFT_IRIS", 0 },
  { "LEFT_LITTLE", 3 },
  { "LEFT_MIDDLE", 4 },
  { "LEFT_RING", 5 },
  { "LEFT_THUMB", 6 },
  { "RIGHT_INDEX", 7 },
  { "RIGHT_IRIS", 1 },
  { "RIGHT_LITTLE", 8 },
  { "RIGHT_MIDDLE", 9 },
  { "RIGHT_RING", 10 },
  { "RIGHT_THUMB", 11 },
  { "UNKNOWN", 12 },
};
const ProtobufCEnumDescriptor in__gov__uidai__authserver__protobuf__position__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "in.gov.uidai.authserver.protobuf.Position",
  "Position",
  "In__Gov__Uidai__Authserver__Protobuf__Position",
  "in.gov.uidai.authserver.protobuf",
  13,
  in__gov__uidai__authserver__protobuf__position__enum_values_by_number,
  13,
  in__gov__uidai__authserver__protobuf__position__enum_values_by_name,
  1,
  in__gov__uidai__authserver__protobuf__position__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
